baseURL = "https://example.com"
languageCode = "en-us"
title = "Food Blog X"
theme = "rocinante"
paginate = 3
summaryLength = 0

[markup]
  defaultMarkdownHandler = "blackfriday"

[author]
  name = "Angela Xia"

[params]
  mainSections = ["post", "photos"]
  email = ""
  favicon = "/icon/favicon.jpg"
  about = """
This is a simple blog about food and more. Enjoy!
(c) 2020 Angela Xia
"""

  [[params.links]]
    [[params.links.link]]
      name = "About"
      href = "/about"
      new_tab = false
